name: ci
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary
      - run: deno lint
      - run: deno fmt --check
      - run: deno test
        continue-on-error: true
